### ISSUE TITLE
Manager closes when using gamebanana mod downloader

### ISSUE THREAD

**Issue by GamingInfinite** [TekkaGB/AemulusModManager#21]
What the title says.  Whenever I download something, it downloads, extracts, then closes.  I feel like this isn't intended somehow.  Just a hunch

**Comment by TekkaGB** [comment]
This was reported to me several times over discord but I can't seem to replicate the issue.  By any chance do you have any antivirus interfering? If not can you try going to the releases and downloading v5.2.3 and let me know if it still crashes when downloading?

**Comment by GamingInfinite** [comment]
Couldn't find anything happening with my antivirus, but reverting back to 5.2.3 helped.  Maybe it's something to do with the loadouts code?  Idk I'm no the expert here

**Comment by TekkaGB** [comment]
Something in the new loadout update is breaking it, just have to pinpoint what exactly since no error message is appearing for some reason.

**Comment by TekkaGB** [comment]
v5.3.3 should fix this, let me know

**Comment by GamingInfinite** [comment]
Tried it this afternoon and it works now.
