### ISSUE TITLE
Support new PCSX2 exes

### ISSUE THREAD

**Issue by soredake** [TekkaGB/AemulusModManager#24]
New 64-bit pcsx2 builds different exes, `pcsx2x64-avx2.exe` for avx2 build and `pcsx2x64.exe` for sse4 build.
https://github.com/PCSX2/pcsx2/actions/runs/1155273443

**Comment by TekkaGB** [comment]
Fixed in https://github.com/TekkaGB/AemulusModManager/commit/1fea95bab24819d4b7797ea168d12e25739d90ce

**Comment by EvanLongMa** [comment]
Now they have new builds using Qt (which eventually may become the main/only version), which have filenames `pcsx2-qtx64.exe` and `pcsx2-qtx64-avx2.exe` respectively currently.

Sources: https://pcsx2.net/downloads/#nightly-anchor
https://github.com/PCSX2/pcsx2/actions/runs/2741120128
