### ISSUE TITLE
Unhandled exception error

### ISSUE THREAD

**Issue by DuIslingr** [TekkaGB/AemulusModManager#29]
Upon opening Aemulus 5.5.3/2 it throws this error. 
![image](https://user-images.githubusercontent.com/19367043/134813543-80cf4baf-72ba-4196-8574-ff42fcc52287.png)

After closing the process continues to run but the window never shows up.

**Comment by TekkaGB** [comment]
Can you zip up and upload your Aemulus Config folder? I can't reproduce the issue on my end
