### ISSUE TITLE
Unhandled Exception Error?

### ISSUE THREAD

**Issue by KittyChat** [TekkaGB/AemulusModManager#31]
![2021-11-03](https://user-images.githubusercontent.com/93690440/140240875-f49c526a-1e4a-45f3-bc01-7492cceeab86.png)

![2021-11-03 (1)](https://user-images.githubusercontent.com/93690440/140240970-8135232e-a45f-4f1a-bc20-519a7dfb5660.png)

When I try opening AemulusPackageManager.exe I get these messages in succession? I've tried redownloading it and making it an exception in my antivirus, but it still won't work. I'm using AemulusPackageManagerv5.5.6

**Comment by TekkaGB** [comment]
Your antivirus might still be blocking it, says that you're missing a file that is included in the download
