### ISSUE TITLE
Persona 3 FES quick launch incompatible with PCSX2 Qt

### ISSUE THREAD

**Issue by bmovoongit** [TekkaGB/AemulusModManager#41]
Using Aemulus to set the pcsx2 exe will lead to a invalid exe error and manually editing the config to add the exe doesn't work either.

**Comment by badspott** [comment]
I can confirm that it also doesn't work with newer versions of PCSX2 Nightly that use wxWidgets based UI. Older version (one I use is PCSX2 Nightly v1.7.2190) launches just fine while the latest one just crashes.

**Comment by ZuwasieMan** [comment]
The mod manager checks the executable name, it should be one of these: pcsx2.exe, pcsx2x64-avx2.exe or pcsx2x64.exe.

**Comment by Pixelguin** [comment]
+1
Aemulus should check if `pcsx2` is anywhere in the executable name instead of whether it is exactly `pcsx2.exe`.

**Comment by TekkaGB** [comment]
Addressed in version 6.2.0
