### ISSUE TITLE
Unable to unpack

### ISSUE THREAD

**Issue by Nubuy** [TekkaGB/AemulusModManager#46]
Hi, I just installed Persona 5 EX and when I tried unpacking the files in Aemulus Package Manager, it said "[ERROR] Failed to unpack everything from Persona 5! Please check if you have all prerequisites installed!" I don't know what I did wrong. Any help?

**Comment by TekkaGB** [comment]
Try installing https://www.microsoft.com/en-us/download/details.aspx?id=26999 then unpack again
