### ISSUE TITLE
P3P mods downloaded through 1 click are downloaded to the wrong folder

### ISSUE THREAD

**Issue by Pioziomgames** [TekkaGB/AemulusModManager#50]
Persona 3 Portable mods downloaded through 1 click on gamebanana are saved to a folder called "Persona 3 Portable (PSP)" instead of the folder that aemulus actually uses for p3p: "Persona 3 Portable"

**Comment by TekkaGB** [comment]
Fixed in https://github.com/TekkaGB/AemulusModManager/commit/53f7729c5f720f13d2a36f2fba8792867c10f6dc
