### ISSUE TITLE
"AemulusPackageManagerv6.1.3.7z" does not download as a zip file (no matter what i use)

### ISSUE THREAD

**Issue by JFZB43** [TekkaGB/AemulusModManager#56]
Whenever i download "AemulusPackageManagerv6.1.3.7z" when being directed from the link it downloads as a html file. When I click it, it opens "internet explorer downloads" and when I click "open" it tries to open a tab, but immediately cancels.

**Comment by TekkaGB** [comment]
https://www.7-zip.org/
