### ISSUE TITLE
ELF file black screen.

### ISSUE THREAD

**Issue by ChaAgiota** [TekkaGB/AemulusModManager#63]
Someone knows how to solve my problem?
I've started to play Persona 3 FES then I wanted to mod it.
I used this video as reference https://www.youtube.com/watch?v=IQ-XzslciHw
The problem is when I boot the game as the ELF file (The emulator screen gets black forever).
Searching about it, other people had the same issue, but I don't understand how to
solve this yet.
I'm using PCSX2 qt 1.7.3522 version.
Would be nice if someone knew how to solve this.

**Comment by TekkaGB** [comment]
Select the iso in the ISO selector then you can launch the elf file.
