### ISSUE TITLE
Unhandled exception occurred:  path '67e715731a908947-938e2a427569678-00006653.dds'.

### ISSUE THREAD

**Issue by Sukai97** [TekkaGB/AemulusModManager#66]
Not too sure how I got here but I basically build a package every 2 installed mods so that I can test run before I add more mods for P3FES. 18 mods in with game still able to run, this error pops up trying to install the next mods. Downloading through the program and drag & drop manually show the same error. Aemuluis folder is located on my desktop.

![error](https://user-images.githubusercontent.com/123377905/214043685-8e59e898-315d-4b7b-b695-e708924d01b6.PNG)

**Comment by destroyer449** [comment]
Delete your temp folder and manually install whatever mod caused it to break.

**Comment by TekkaGB** [comment]
Should be fixed in 6.4.2
