### ISSUE TITLE
Unhandled Exception Occured: Could not find a part of the path '94143fe31e79b8ed-34f0bffdab3ef387-00006653.dds'.

### ISSUE THREAD

**Issue by AoiRice** [TekkaGB/AemulusModManager#69]
Installing from Aemulus, 1-click Install, manual drag and drop, all install methods keep posting the same error. This error hadn't shown up until recently after trying to update to the latest versions of New Moon and Elemental Icons for Skills. Aemulus folder is in my C: drive.

Took a second to dig around and found out the file that the error is referring to seems to be located in the Aemulus temp folder within a folder named "widescreen_persona_artwork_fixes_95d7e". 

Issues identical to this one have already been reported a few times before, and all seem to stem from a widescreen fix mod.
![aemuluserror](https://user-images.githubusercontent.com/38058414/214520553-9750df27-f34b-4597-883f-5f95bac4f0de.png)

**Comment by TekkaGB** [comment]
Should be fixed in 6.4.2
