### ISSUE TITLE
Everytime I try to install a mod i get: Unhandled exception occured: Could not find a part of the path '94143fe31e79b8ed-34f0bffdab3ef38700006653.dds'

### ISSUE THREAD

**Issue by ColemakDH** [TekkaGB/AemulusModManager#70]
As the title says everytime I try to install a new mod I get that error, it doesn't matter what I do, if I reinstall I can install like 4 mods and then it starts doing it again, no idea what the problem is and I've seen multiple people with the same error and no solution on reddit, does anyone here know what's going on?

![aemulus](https://user-images.githubusercontent.com/75554620/215360503-d12c6d13-4421-4564-a241-69ca3535625a.JPG)

**Comment by destroyer449** [comment]
This is a well known issue with P3 modding. It is caused when mods make use of folders or have very long names, such that the expanded path of the file at build time is 248 or more characters. Currently you can get around this limitation deleting your aemulus temp folder and installing the mod that has the char limit manually. As of #72 this should be fixed.
