### ISSUE TITLE
Unhandeled exception occured could not load file or assembly yada yada when I try to open, and happens when I try to open the program, still happenes when I downloaded it again and restarted my computer

### ISSUE THREAD

**Issue by SomeonetookSomeonetookmeep** [TekkaGB/AemulusModManager#76]
Unhandeled exception occured could not load file or assembly yada yada when I try to open, and happens when I try to open the program, still happenes when I downloaded it again and restarted my computer

![image](https://user-images.githubusercontent.com/105999150/221395435-40768d0d-3aae-4c0a-bf3f-8ea4c55ceb88.png)

**Comment by SomeonetookSomeonetookmeep** [comment]
Then this after I "Ok" or close the previous"

**Comment by leoclubs** [comment]
i got the same exact issue after updating to 6.4.2

**Comment by TekkaGB** [comment]
Sorry, forgot to include some files. Please redownload the latest release and manually extract it to your aemulus folder

**Comment by SomeonetookSomeonetookmeep** [comment]
Thank You!
