### ISSUE TITLE
The '-gui' part of the latest hotfix breaks the launcher

### ISSUE THREAD

**Issue by Grey421** [TekkaGB/AemulusModManager#77]
I installed the update, loaded a couple new mods via the installer and clicked launch, and it didn't launch because apparently PCSX2 didn't recognise the 'nogui' argument. I don't know why this was changed unless there's some PCSX2 update that I missed (I'm on 1.6.0, latest stable release) and it seemingly does nothing except break the launcher. If it's an update made to function with the nightly function, could it please be at least reduced to a setting in the configuration menu?

**Comment by TekkaGB** [comment]
Oh yeah, for some reason pcsx2 devs changed --nogui arg to be -nogui in latest 1.7 builds. I forgot to account for people still in 1.6.0.  You can always update pcsx2 to 1.7 or wait for me to add a config change

**Comment by TekkaGB** [comment]
Or you can also just manually run the elf in pcsx2

**Comment by TekkaGB** [comment]
Fixed in 6.4.3 release
