### ISSUE TITLE
Unpack base file error "Could not load file or assembly CriFsV2Lib.Definition (i try for p5r on yuzu)

### ISSUE THREAD

**Issue by flayhender** [TekkaGB/AemulusModManager#91]
Well i think i put my output folder my rom path and my emulator path correctly but when i click unpack base file it open the explorer menu and the lony way i dont have the 'not all cpks needed" thing at the bottom is to go through C:/Games/Persona 5 Royal/user/dump/01005CA01580E000/romfs/cpk and i believ its not supossed to go through this all so i just dont understand what im doing wrong a bit help would be appreciated !

**Comment by MetaheuristicaCucei** [comment]
Same problem but for Persona 3 Portable unpacking

**Comment by TekkaGB** [comment]
Should be fixed with version 6.5.2
