### ISSUE TITLE
unhandled exeption occured

### ISSUE THREAD

**Issue by L3v1tje** [TekkaGB/AemulusModManager#92]
hey so im new to modding so i might have done a goof but i cant seem to get aemulus to launch my game. i keep getting this error. 
![Screenshot 2023-11-04 211411](https://github.com/TekkaGB/AemulusModManager/assets/26630155/fa8aac84-a9d9-46b4-a280-75247c133338)
how can i fix it? i also get this error when pressing the setup and support me buttons.
it is for Persona 5 strikers btw.

**Comment by TekkaGB** [comment]
Should be fixed with version 6.5.2
