### ISSUE TITLE
Not unpacking init_free.bin, init.bin, init_2.bin or init_2F.bin or it's paths anymore.

### ISSUE THREAD

**Issue by BonQerss** [TekkaGB/AemulusModManager#99]
Aemulus no longer unpacks init bin files or their respective path for new users. I get about a comment or two every week claiming that my mods are broken when the user is purely missing their init_free.bin file. Started happening after the .NET 8.0 upgrade. Old users are affected too as it removed the init_free.bin file from your original folder too it seems.

**Comment by TekkaGB** [comment]
Fixed the issue with the latest release, turns out the "/" before the filename in the csvs didn't work with the new cpk library. Removed the "/" and now they unpack
